apiVersion: "v1"
kind: Service
metadata:
  name: "dbmage2-service"
 
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: "dbmage2"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volclaim
spec:
  storageClassName: manual       
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dbmage2"
  labels: 
    app: "dbmage2"
spec:
  replicas: 1
  selector:
    matchLabels:
        app: "dbmage2"
  template:
    metadata:
      labels:
        app: "dbmage2"
    spec:
      containers:
        - name: "dbmage2"
          image: "mysql:5.6.23"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_HOST
              value: "dbmage2-service.magento2.svc.cluster.local"
            - name: MYSQL_ROOT_PASSWORD
              value: myrootpassword
            - name: MYSQL_USER
              value: magento
            - name: MYSQL_PASSWORD
              value: magento
            - name: MYSQL_DATABASE          
              value: magento


          volumeMounts:
            - name: "volclaim-mysql"
              mountPath: "/var/lib/mysql"
      volumes:
        - name: "volclaim-mysql"
          persistentVolumeClaim:
            claimName: mysql-volclaim
